# Copyright 2022 Dhi Aurrahman
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
---
name: "commit"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

  # Allows triggering the workflow manually in github actions page.
  workflow_dispatch:

defaults:
  run: # use bash for all operating systems unless overridden.
    shell: bash

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-20.04
    timeout-minutes: 90 # instead of 360 by default.
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true # Checks out submodules.
      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: "Setup cache for Go"
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum', 'Tools.mk') }}
          restore-keys: ${{ runner.os }}-go-
      - name: "Setup cache for Tools"
        uses: actions/cache@v2
        with:
          path: ./.cache/tools
          key: ${{ runner.os }}-tools-${{ hashFiles('Tools.mk') }}
      - name: "Generate cache key for Linter"
        run: |
          echo "::set-output name=name::$(/bin/date -u "+%Y%m%d")"
        id: get-cache-key
      # We generate a new key golangci-lint run per day.
      - name: "Setup cache for Linter"
        uses: actions/cache@v2
        with:
          path: ./.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('go.mod') }}-${{ steps.get-cache-key.outputs.name }}
          restore-keys: ${{ runner.os }}-golangci-lint-
      - run: make check
      - run: make test
